/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Andy Ruiz
 */
public class GUIMenu extends javax.swing.JFrame {
    
	private static final long serialVersionUID = -5153802458305216944L;
	private UserMenu windowManager;
    
    
    /**
     * Creates new form MainMenu
     */
    public GUIMenu() {
        initComponents(); 
    }
    
    public void setup(UserMenu manager){
        this.setVisible(false);
        this.windowManager = manager;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fazerPrevisao = new javax.swing.JButton();
        verPrevisoes = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAvisos = new javax.swing.JTextPane();
        fazerPrevisao1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/oie_transparent.png"))); // NOI18N

        fazerPrevisao.setText("Fazer previsão");
        fazerPrevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerPrevisaoActionPerformed(evt);
            }
        });

        verPrevisoes.setText("Ver previsões");
        verPrevisoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPrevisoesActionPerformed(evt);
            }
        });

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Open16.gif"))); // NOI18N
        openButton.setText("Open File...");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        textAvisos.setEditable(false);
        textAvisos.setBackground(new java.awt.Color(204, 204, 204));
        textAvisos.setBorder(null);
        textAvisos.setText("Selecione arquivo de entrada contendo as Rubricas...");
        textAvisos.setAlignmentY(1.0F);
        textAvisos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textAvisos.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        textAvisos.setEnabled(false);
        jScrollPane1.setViewportView(textAvisos);

        fazerPrevisao1.setText("Modificar PrevisÃ£o");
        fazerPrevisao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerPrevisao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(fazerPrevisao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(212, 212, 212))))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(fazerPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verPrevisoes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verPrevisoes)
                    .addComponent(fazerPrevisao))
                .addGap(29, 29, 29)
                .addComponent(fazerPrevisao1)
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Usa o navegador do Swing para procurar um arquivo .csv e retorna seu path
    * Passa esse path do arquivo para o windowController
    */
    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos csv", "csv");
        File f;
        fc.setFileFilter(filter);
        fc.showOpenDialog(null);
        try {
            f = fc.getSelectedFile();
            if(f.exists())
            {
                String filePath = f.getAbsolutePath();
                windowManager.loadMenuFile(filePath);
            }
        } catch (Exception NullPointerException) {
            setAviso("Por favor selecione um arquivo contendo as Rubricas para poder prosseguir com a aplicação.");
        }
    }//GEN-LAST:event_openButtonActionPerformed

    /*
    * Dada uma string a mostra para o usuario na caixa de avisos
    */
    protected void setAviso(String message){
        textAvisos.setText(message);
    }
    private void fazerPrevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerPrevisaoActionPerformed
        windowManager.openPrevisionWindow();
    }//GEN-LAST:event_fazerPrevisaoActionPerformed

    private void verPrevisoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPrevisoesActionPerformed
       windowManager.viewCalculatedPrevisions();
    }//GEN-LAST:event_verPrevisoesActionPerformed

    private void fazerPrevisao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerPrevisao1ActionPerformed
        windowManager.modifyActualPrevision();
    }//GEN-LAST:event_fazerPrevisao1ActionPerformed

    /*
    * MÃ©todo apenas para inserir na caixa de avisos ao usuario uma mensagem para escolher arquivo
    */
    @SuppressWarnings("unused")
	private void askLoadFile(){
        textAvisos.setText("Nenhum arquivo válido foi selecionado!\nPor favor selecione o arquivo de entrada contendo as Rubricas. ");
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fazerPrevisao;
    private javax.swing.JButton fazerPrevisao1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openButton;
    private javax.swing.JTextPane textAvisos;
    private javax.swing.JButton verPrevisoes;
    // End of variables declaration//GEN-END:variables

    /*
    * Deshabilita o botao para carregar um arquivo
    */
    void disableFileLoader() {
        openButton.setEnabled(false);
    }

    /*
    * Abre a janela
    */
    void OpenWindow() {
        this.setVisible(true);
        
    }
    
    /*
    * Fecha a janela
    */
    void closeWindow() {
        this.setVisible(false);
        
    }
}
